version: 3

tasks:
  create:site:
  - hugo new site windkube

  download:theme:onelou:
    cmds:
    - git clone https://github.com/jyygithub/hugo-theme-onelou.git onelou
    - rm -rf onelou/.git

  run:local: 
    dir: onelou
    cmds:
    - hugo server -D 